# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Docs(æ‰‹åŠ¨å‘å¸ƒ)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "To release (e.g., major | minor | patch | premajor | preminor | prepatch | prerelease | x.x.x)"
        required: false
      parameter_for_publish:
        description: "parameter for publish"
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v2
        id: yarn_cache
        with:
          path: "**/node_modules"
          key: modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            modules-${{ hashFiles('**/yarn.lock') }}
            modules-

      - name: install node_modules if cache missed
        if: steps.yarn_cache.outputs.cache-hit != 'true'
        run: yarn install --use-workspaces

  publish:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install node_modules ğŸ’¡
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            modules-${{ hashFiles('**/yarn.lock') }}
            modules-

      - name: build ğŸ”§
        run: |
          cd packages/docs
          yarn docz:build --dest ../../docs

      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs
          publish_branch: gh-pages
          keep_files: true
